### ISSUE TITLE
Possibility of obtaining list of all points

### ISSUE THREAD

**Issue by divios** [YiC200333/MPoints#3]
Hi!

I was checking the api and i wonder if it could be possible to add a method that returns a list of all the points created so far?

**Comment by YiC200333** [comment]
OK, I will add this api

**Comment by divios** [comment]
hi! Is it already available?

**Comment by YiC200333** [comment]
I'll update it this week.

**Comment by divios** [comment]
alright thanks! looking forward to it

**Comment by YiC200333** [comment]
https://github.com/YiC200333/MPoints/releases/tag/1.1.12

**Comment by YiC200333** [comment]
https://github.com/YiC200333/MPoints/releases/tag/1.1.12

**Comment by divios** [comment]
thanks man!
