### ISSUE TITLE
插件不支持Vault吗

### ISSUE THREAD

**Issue by junxiesky** [YiC200333/MPoints#4]
从XConomy换过来的，发现从插件不支持Vault
导致服务器的商店等无法使用
请问怎么解决？

**Comment by YiC200333** [comment]
MPoints，不支持Vault，可以配合XConomy使用

**Comment by junxiesky** [comment]
> MPoints，不支持Vault，可以配合XConomy使用

好的，那么商店插件该如何调用MPoints的货币呢？
是需要插件对MPoints进行适配支持吗

**Comment by YiC200333** [comment]
只要商店插件支持placeholder变量
就可以使用placeholder的变量进行余额判断

**Comment by YiC200333** [comment]
详细变量参考mcbbs或者spigot的帖子

**Comment by junxiesky** [comment]
> 详细变量参考mcbbs或者spigot的帖子

好的
