### ISSUE TITLE
add %mpoints_<pointsign>_top_hide% + dynamic eco

### ISSUE THREAD

**Issue by xuandattnvn1995** [YiC200333/MPoints#6]
same:
https://github.com/YiC200333/XConomy/issues/115

add %mpoints_<pointsign>_top_hide% = true/false
balancetop display => %xconomy_top_hide% = false
balancetop hide => %xconomy_top_hide% = true
This helps me create a gui so players can hide/show their information on the top.

add dynamic eco.
%mpoints_<pointsign>_dynamic%
%mpoints_<pointsign>_dynamic_formatted%
points.yml
![image](https://github.com/YiC200333/MPoints/assets/25878455/ccd64a9d-aa9c-4e0f-b325-0af4ddd6033c)

**Comment by YiC200333** [comment]
MPoints temporarily won't add this feature
