### ISSUE TITLE
error 2.0.5

### ISSUE THREAD

**Issue by xuandattnvn1995** [YiC200333/MPoints#7]
**Version of MPoints**  
MPoints-Paper-2.0.5

**Server version**  
paper 1.20.1 #194

1. tab complete error
![image](https://github.com/YiC200333/MPoints/assets/25878455/a9b313f4-cb0f-4a2e-9876-188779712789)
2. message error
![image](https://github.com/YiC200333/MPoints/assets/25878455/4fe4ba95-5cbd-4d9d-a52a-b3a1c56c93ad)
3. cmd mpoints list = mpoints help
![image](https://github.com/YiC200333/MPoints/assets/25878455/385c6dc6-8b2c-4cae-85a8-8d3104fafb1e)
4. cmd error:  /[sign] give/set/take [name] [amount]
![image](https://github.com/YiC200333/MPoints/assets/25878455/6b86a613-0e5b-4ae8-abd7-cc01c6332e82)
![image](https://github.com/YiC200333/MPoints/assets/25878455/f9a5a721-07a3-4a39-81a4-f6883c702ded)
5. cmd:  /[sign] give/set/take * [all/online] [amount] [reason] Cannot set empty reason
![image](https://github.com/YiC200333/MPoints/assets/25878455/5644a752-797f-443e-9a7e-39465e571908)

**Comment by YiC200333** [comment]
The problem is fixed
give/set/take * [all/online] [amount] [reason] 
This command must be add the reason
